//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Apartment
    {
        [Key]
        public int ApartmentId { get; set; }

        [DisplayName("Building")]
        [Required]
        public int BuildingId { get; set; }
        [DisplayName("Apartment Number")]
        [Required]
        public int ApartmentNumber { get; set; }

        [Required]
        public int Floor { get; set; }

        [DisplayName("Number of rooms")]
        [Required]
        public int NumberOfRooms { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public string Status { get; set; }

        public Nullable<int> TenantId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
