//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.Apartments = new HashSet<Apartment>();
        }
    
        [Key]
        public int BuildingId { get; set; }

        [DisplayName("Street Number")]
        [Required(ErrorMessage = "This field is required")]
        public int StreetNumber { get; set; }

        [DisplayName("Street Name")]
        [Required(ErrorMessage = "This field is required")]
        public string StreetName { get; set; }

        [DisplayName("Postal Code")]
        [Required(ErrorMessage = "This field is required")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string City { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Province { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartments { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
